# -*- coding: utf-8 -*-
"""front.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1066fshvxw65CrT3xjO90o4K7wgD65Zwb
"""

def EFF_FRONT( ASSETS , START , END , POINTS , R_FREE):
  def MONTHLY_RETURNS(SYMBOLS , FROM , TO):
    from yfinance import download
    DATA = download(tickers=SYMBOLS ,
                    start=FROM, end=TO)
    ADJUSTED = DATA["Adj Close"]
    DAILY = ADJUSTED.pct_change()
    import quantstats as qs
    MONTHLY = qs.utils.aggregate_returns(returns=DAILY , period="M")
    from pandas import date_range
    MONTHLY.index = date_range(start=FROM, end=TO , freq="M")
    return MONTHLY
  EGGS = MONTHLY_RETURNS(SYMBOLS=ASSETS , FROM=START , TO=END)
  import riskfolio as rf
  OBJECT = rf.Portfolio(returns=EGGS)
  OBJECT.assets_stats()
  WEIGHTS = OBJECT.efficient_frontier(points=POINTS)
  PLOT = rf.plot_frontier(w_frontier=WEIGHTS , mu=OBJECT.mu , cov=OBJECT.cov , returns=EGGS , rf=R_FREE , t_factor=1)
  ALL = WEIGHTS.T
  XY = PLOT.collections[0].get_offsets()
  ALL[["STD. DEV." , "EXP. MONTHLY RET."]] = XY
  ALL["SHARPE RATIO"] = (ALL['EXP. MONTHLY RET.'] - R_FREE) / ALL['STD. DEV.']
  ALL["SHARPE RATIO"]  =  round( ALL["SHARPE RATIO"] , 4)
  import plotly.express as px
  INTERACTIVE = px.scatter(
      data_frame=ALL,
      x="STD. DEV.",
      y="EXP. MONTHLY RET.",
      color="SHARPE RATIO" ,
      title="Efficient Frontier" ,
      hover_data = { X  : ":.2%"
                    for X in ALL.columns[:-1] } )
  INTERACTIVE.update_layout(
        template="plotly_dark" ,
      font_family="Courier New" ,
      hoverlabel={"font_family" : "Courier New" ,
                      "bgcolor" : "black"} )
  return INTERACTIVE