---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
#IST772 12-20-2022
#Sintia Stabel 

```{r}

library(readxl)
read_excel('C:\\Users\\sinti\\Syracuse University\\IST772\\newDist.xlsx')
read_excel('C:\\Users\\sinti\\Syracuse University\\IST772\\districtst.xlsx')
read_excel('C:\\Users\\sinti\\Syracuse University\\IST772\\DF.xlsx')
read_excel( 'C:\\Users\\sinti\\Syracuse University\\IST772\\AllSchools.xlsx')
#DATA EXPLORATIO AND TRANSFORMATION
#USVaccines <- as.data.frame.matrix(usVaccines)
#str(USVaccines)

#head(usVaccines)

DF <- cbind(year,USVaccines)

year <- c(1980:2017)
library(tidyverse)

#head(DF)

boxplot( DF$year ~ DF$MCV1, data=DF, 
         main="WHO - US Vaccination Rates by Year", 
         xlab="Vaccines", col="seagreen3")

plot(DF$year, DF$DTP1)
plot(DF$year,DF$HepB_BD)
plot(DF$year, DF$MCV1)
plot(DF$year, DF$Pol3)
plot(DF$year, DF$Hib3)
plot(DF$year, DF$MCV1)

#library(ggplot2)

AllVacs <-ggplot(DF,aes(x= DTP1+ HepB_BD+MCV1 + Pol3+ Hib3 + MCV1, y = year))+ 
  geom_point()+geom_smooth(method="lm")
  #ggtitle("Premium Annual Cost against Multiple Factors")
  #+labs(y="Premium Price",x="Significant Variables")
  
head(AllVacs)


# Transforming columns in distritct from percent without to percent with vaccines

head(Dist)
#Dist <- districts

PctDTP <- abs(Dist$WithoutDTP - 100)
PctPolio <- abs(Dist$WithoutPolio - 100)
PctMMR <- abs(Dist$WithoutMMR - 100)
PctHepB <- abs(Dist$WithoutHepB - 100)

# adding new columns and dropping the percent without ones

newDist <- cbind(Dist,PctDTP,PctPolio,PctMMR,PctHepB)

newDist <- subset(newDist, select = -c(2:5))

head(newDist)
#AllSchools <- allSchoolsReportStatus
tail(AllSchools)

#############

#install.packages('writexl')
#library(writexl)

#write_xlsx(newDist, 'C:\\Users\\sinti\\Syracuse University\\IST772\\newDist.xlsx')
#write_xlsx(districts, 'C:\\Users\\sinti\\Syracuse University\\IST772\\districtst.xlsx')
#write_xlsx(DF, 'C:\\Users\\sinti\\Syracuse University\\IST772\\DF.xlsx')
#write_xlsx(AllSchools, 'C:\\Users\\sinti\\Syracuse University\\IST772\\AllSchools.xlsx')
####################
```

```{r}
# QUESTION 1:
#How have U.S. vaccination rates varied over time? 
# a Are vaccination rates increasing or decreasing? 
# b Which vaccination has the highest rate at the conclusion of the time series? 
# c Which vaccination has the lowest rate at the conclusion of the time series?
# d Which vaccine has the greatest volatility? 
  

summary(usVacs)
head(usVacs)
 usVacs <-DF

plot.ts(justVacs,
        main = "US Vaccination Rates 1980-2017")
scatterplot(usVacs$year, usVacs$MCV1,
     main = "MCV1 Vaccination Rate")
     
scatterplot(usVacs$year, usVacs$Pol3,
     main = "Polio Vaccination Rate")
plot(usVacs$year, usVacs$MCV1)

# removing the year
justVacs <- subset(usVacs, select =-c(1))
head(justVacs)


# plotting volatility of the difference
plot(diff(usVaccines),
     main=" Volatility US Vaccination Rates 1980-2017")
   



```


```{r}
#2.	What proportion of public schools reported vaccination data? 
# What proportion of private schools reported vaccination data?
# Was there any credible difference in overall reporting proportions
# between public and private schools? 
#library(tidyverse)
#library(readxl)
allSchools <- read_excel('C:\\Users\\sinti\\Syracuse University\\IST772\\AllSchools.xlsx')

#proportion of public schools who reported vaccination

pubReported <- allSchools %>% filter(pubpriv == 'PUBLIC', reported == "Y")

privReported <- allSchools %>% filter(pubpriv == 'PRIVATE', reported == 'Y')

#Percentage of Private schools that reported out of total reporting schools
print(sum(privReported$zero_one))/(sum(allschools$reported))

#Percentage of Public schools that reported out of total reporting schools
print(sum(pubReported$zero_one))/(sum(allschools$reported))

print(sum(allschools$reported))

str(allschools)

head(allSchoolsReportStatus)

allSchoolsReportStatus$isPublic <- as.numeric(allSchoolsReportStatus$pubpriv=="PUBLIC")

allSchoolsReportStatus$isReported <- as.numeric(allSchoolsReportStatus$reported=="Y")

t_test <- t.test(allSchoolsReportStatus$isReported[allSchoolsReportStatus$isPub==1],
                 
                 allSchoolsReportStatus$isReported[allSchoolsReportStatus$isPublic==0])

t_test

#library(BEST) 
#library(rjags)


# Unable to run BESTmcmc

 #MCMC_test <- BESTmcmc(allSchoolsReportStatus$isReported[allSchoolsReportStatus$isPub==1],                 allSchoolsReportStatus$isReported[allSchoolsReportStatus$isPublic==0])

#plot(MCMC_test) 

```

```{r}
# Question 3
#	What are 2013 vaccination rates for individual vaccines (i.e., DOT, Polio, MMR, and HepB) 
# in California public schools?  How do these rates for individual vaccines
#in California districts compare with overall US vaccination rates
#(make an informal comparison to the final observations in the time series)? 
  
head(newDist) # data inspection
head(usVacs) # data inspection

# California District Data
vacc2013 <- newDist[,10:13] # sub-setting the data to have only the columns with vaccination rates
str(vacc2013) # 700 observations we know from the description the data set is for the year 2013

mean(vacc2013$PctDTP) # mean DTP
mean(vacc2013$PctHepB)# mean HepB
mean(vacc2013$PctPolio)# mean Polio
mean(vacc2013$PctMMR) # mean MMR


boxplot(vacc2013,
        main = 'California Districts Vaccination Rates') # rates for all 4 vaccines
summary(vacc2013)

#WHO US data
usVacs_2013 <- usVacs %>% filter(usVacs$year == "2013") # WHO US rates for vaccines for year 2013
usVacs_2013 # results of  WHO US rates for vaccines for year 2013
str(usVacs) # 38 obs
usVacs_2017 <- usVacs[38,]
```

```{r}

# Question 4
#	Among districts, how are the vaccination rates for individual vaccines related? In other words,
# if students are missing one vaccine are they missing all of the others?

# sub-setting for complete reporting only

str(newDist)
Districts <- newDist %>% filter(DistrictComplete == 'TRUE')
str(Districts)
library(tidyverse)
# sub-setting for relevant numerical vars

#RevDistrictsVars <- Districts %>% select(PctUpToDate, PctUpToDate, PctBeliefExempt, PctChildPoverty, PctFamilyPoverty,PctFreeMeal,PctDTP, PctHepB, PctMMR, PctPolio)                       
                                 

#str(RevDistrictsVars)
cor(RevDistrictsVars)


scatterplot(x= RevDistrictsVars$PctChildPoverty,
            y = RevDistrictsVars$PctFreeMeal,
            main = "% Child Poverty vs % Free Meal")

scatterplot(x= RevDistrictsVars$PctUpToDate, 
            y = RevDistrictsVars$PctBeliefExempt,
            main = "% Believe Exempt vs % Up-to-Date")

scatterplot(x= RevDistrictsVars$PctPolio,
            y = RevDistrictsVars$PctDTP,
            main = "% Polio vs % DTP ")

```

```{r}
# Question 5 
# What variables predict whether or not a district’s reporting was complete?


# Grouping the data into two groups

newDist$DistrictComplete[newDist$DistrictComplete == "1"] <- "1" # report is complete
newDist$DistrictComplete[newDist$DistrictComplete == "2"] <- "0"# report is not complete

newDist$DistrictComplete <- as.numeric(newDist$DistrictComplete) 

# calling required libraries

#library(BaylorEdPsych)
#library(car)
#library(MCMCpack)
#library(BEST)

#Logistic Regression

#glm_DistrictComplete <- glm(formula = DistrictComplete ~ PctChildPoverty + PctFreeMeal +
                #PctFamilyPoverty + Enrolled + TotalSchools, family = binomial(), data = newDist)
#Output of Logistic Regression
summary(glm_DistrictComplete)

# Bayes MCMCLogit
#glm_DistrictCompleteBayes <- MCMClogit(formula=DistrictComplete ~ Enrolled
                                      # + TotalSchools, data=newDist)
                                   
summary(glm_DistrictCompleteBayes)

# Plot of MCMCLogit
plot(glm_DistrictCompleteBayes)

```

```{r}
# Question 6
#	What variables predict the percentage of all enrolled students with completely up-to-date vaccines?


# Linear Regression
PctUpToDate_lm <- lm(formula = PctUpToDate ~ PctChildPoverty + PctFreeMeal + PctFamilyPoverty + Enrolled
            + TotalSchools, data = newDist)
# Output of Linear Regression
summary(PctUpToDate_lm)

# Test for Multicollinearity
vif(PctUpToDate_lm)

# Linear Regression after vif()
PctUpToDate_lm2 <- lm(formula = PctUpToDate ~ PctChildPoverty +PctFreeMeal
                 + PctFamilyPoverty , data = newDist)
# Output afeter vif()
summary(PctUpToDate_lm2)

# Bayes Factor Linear Model
PctUpToDate_BF <- lmBF(PctUpToDate ~ PctChildPoverty+ 
                    PctFamilyPoverty, data=newDist,posterior=F)
summary(PctUpToDate_BF)
```

```{r}
# Question 7 
#What variables predict the percentage of all enrolled students with belief exceptions?
#library(BaylorEdPsych)
# Linear Regression
PctBeliefExempt_lm <- lm(formula = PctBeliefExempt ~ 
                           PctChildPoverty + PctFreeMeal + PctFamilyPoverty
                         + Enrolled + TotalSchools, data = newDist)

# Output Linear Regression
summary(PctBeliefExempt_lm)

# 2nd Linear Regression
PctBeliefExempt_lm_2 <- lm(formula = PctBeliefExempt ~ PctChildPoverty +
                             PctFreeMeal + PctFamilyPoverty,data = newDist)

# Output of 2nd Linear Regression
summary(PctBeliefExempt_lm_2)

# Test for Multicollinearity
vif(PctBeliefExempt_lm)

# Bayes Factor Linear Model
PctBeliefExempt_BF <- lmBF(PctBeliefExempt ~ PctChildPoverty + PctFreeMeal

                            + PctFamilyPoverty, data=newDist,posterior=F)
#Output of Bayes Factor Linear Model
summary(BFOut)
```

```{r}

#Question 8
#What’s the big picture, based on all of the foregoing analyses?
#The staff member in the state legislator’s office is interested to know 
#how to allocate financial assistance to school districts to improve
#both their vaccination rates and their reporting compliance.
#What have you learned from the data and analyses that might inform this question?

```
